// dev
const DEV_CHANNEL_ID = "C0616PTQ6AF";

// test
const TEST_CHANNEL_ID = "C060S2Z6E15";

// prod
const PROD_CHANNEL_ID = "C05CMTDNZ89";



const TARGET_CHANNEL_ID = PROD_CHANNEL_ID;

export { TARGET_CHANNEL_ID, DEV_CHANNEL_ID, TEST_CHANNEL_ID, PROD_CHANNEL_ID };
